- include_role:
    name: yatesr.timezone

- name: Update apt packages
  become: true
  apt:
    update_cache: yes
    cache_valid_time: 86400 #One day

- name: Install common packages
  apt: name={{ item }} state=latest
  loop: [docker.io, libffi-dev, python3-pip, curl, jq]
  become: yes
